/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Close: typeof import('./src/components/icons/Close.vue')['default']
    Delete: typeof import('./src/components/icons/Delete.vue')['default']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElText: typeof import('element-plus/es')['ElText']
    PostCountSelect: typeof import('./src/components/PostCountSelect.vue')['default']
    PostDraggable: typeof import('./src/components/PostDraggable.vue')['default']
    PostHeader: typeof import('./src/components/PostHeader.vue')['default']
    PostList: typeof import('./src/components/PostList.vue')['default']
    PostListItem: typeof import('./src/components/PostListItem.vue')['default']
    PostOrganizer: typeof import('./src/components/PostOrganizer.vue')['default']
    PostPagination: typeof import('./src/components/PostPagination.vue')['default']
    PostSearch: typeof import('./src/components/PostSearch.vue')['default']
    PostViewer: typeof import('./src/components/PostViewer.vue')['default']
    Search: typeof import('./src/components/icons/Search.vue')['default']
    UiAutocomplete: typeof import('./src/components/ui/UiAutocomplete.vue')['default']
    UiCard: typeof import('./src/components/ui/UiCard.vue')['default']
    UiCloseButton: typeof import('./src/components/ui/UiCloseButton.vue')['default']
    UiDataList: typeof import('./src/components/ui/UiDataList.vue')['default']
    UiDelete: typeof import('./src/components/ui/UiDelete.vue')['default']
    UiDraggable: typeof import('./src/components/ui/UiDraggable.vue')['default']
    UiEmpty: typeof import('./src/components/ui/UiEmpty.vue')['default']
    UiInput: typeof import('./src/components/ui/UiInput.vue')['default']
    UiInputSearch: typeof import('./src/components/ui/UiInputSearch.vue')['default']
    UiLoader: typeof import('./src/components/ui/UiLoader.vue')['default']
    UiPagination: typeof import('./src/components/ui/UiPagination.vue')['default']
    UiSelect: typeof import('./src/components/ui/UiSelect.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
