/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElAutocomplete: typeof import('element-plus/es')['ElAutocomplete']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLayout: typeof import('element-plus/es')['ElLayout']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElText: typeof import('element-plus/es')['ElText']
    PageFooter: typeof import('./src/components/PageFooter.vue')['default']
    PageHeader: typeof import('./src/components/PageHeader.vue')['default']
    PostCountSelect: typeof import('./src/components/PostCountSelect.vue')['default']
    PostHeader: typeof import('./src/components/PostHeader.vue')['default']
    PostItem: typeof import('./src/components/PostItem.vue')['default']
    PostList: typeof import('./src/components/PostList.vue')['default']
    PostListItem: typeof import('./src/components/PostListItem.vue')['default']
    PostLoader: typeof import('./src/components/PostLoader.vue')['default']
    PostOrganizer: typeof import('./src/components/PostOrganizer.vue')['default']
    PostPagination: typeof import('./src/components/PostPagination.vue')['default']
    PostSearch: typeof import('./src/components/PostSearch.vue')['default']
    PostViewer: typeof import('./src/components/PostViewer.vue')['default']
    Search: typeof import('./src/components/icons/Search.vue')['default']
    UiAutocomplete: typeof import('./src/components/ui/UiAutocomplete.vue')['default']
    UiCard: typeof import('./src/components/ui/UiCard.vue')['default']
    UiDataList: typeof import('./src/components/ui/UiDataList.vue')['default']
    UiEmpty: typeof import('./src/components/ui/UiEmpty.vue')['default']
    UiInput: typeof import('./src/components/ui/UiInput.vue')['default']
    UiInputSearch: typeof import('./src/components/ui/UiInputSearch.vue')['default']
    UiLoader: typeof import('./src/components/ui/UiLoader.vue')['default']
    UiPagination: typeof import('./src/components/ui/UiPagination.vue')['default']
    UiSelect: typeof import('./src/components/ui/UiSelect.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
